star_tool:
  /home/groups/CEDAR/tools/STAR/tags/2.5.3a/bin/Linux_x86_64/STAR

star_index:
  /home/groups/CEDAR/anno/igenomes/Homo_sapiens/UCSC/hg19/Sequence/StarIndex

project_id:
  BAML 

base_dir:
  /home/exacloud/tempwork/CompBio/users/estabroj/BAML_exoncentric_analysis/exon-centric-pipeline 

omic_meta_data:
  # tab delimited file
  #/home/exacloud/tempwork/CompBio/users/estabroj/BAML_exoncentric_analysis/exon-centric-pipeline/data/CTD2_w_asxl_status_meta.tsv
  /home/exacloud/tempwork/CompBio/users/estabroj/BAML_exoncentric_analysis/exon-centric-pipeline/data/Subset_asxl_meta.tsv

gtf_file:
  /home/groups/CEDAR/anno/igenomes/Homo_sapiens/UCSC/hg19/Sequence/StarIndex/genes.gtf

gff:
  /home/groups/CEDAR/estabroj/annotations/gff3/hg19/SE.hg19.gff3

event_type:
  # Type of exon-event i.e. SE: skipped exon, MXE: mutually exclusive exons, etc.
  SE

baseline:
  #Baseline for linear model - needs to be a factor in column listed for : linear_model 
  WT

linear_model:
  #Column name in meta data file to generate contrasts by
  Condition

sample_id:
  #Column name listing unique sample ids to be used. This needs to be the first column in the meta data file
  SampleID

assembly:
  hg19

const_exons:
  /home/groups/CEDAR/estabroj/annotations/gff3/hg19_cons_exons/SE.hg19.min_1000.const_exons.gff

events:
  /home/groups/CEDAR/estabroj/annotations/gff3/hg19/indexed_SE_events

read_length:
  100

minbayes:
    5

shuffles:
    100

pca:
  labels:
    #Column name in meta data file to generate group files and comparisons
    - Condition

diffexp:
  # contrasts to generate group files and perform comparisons
  contrasts:
    # baseline-vs-contrast:
    #   - contrast 
    #   - baseline

    control-vs-asxl:
      - control
      - ASXL_mutant
#    control-vs-Other:
#      - control
#      - Other

