import os
import subprocess
eventDir = os.path.join(os.getcwd(), snakemake.input)
outDir = os.path.join(os.getcwd(),'samples/miso/comparisons')
samples = sorted(os.listdir(snakemake.input))
base_dir = os.getcwd()
submission_dir = os.path.join(os.getcwd(),'submission_scripts')
for i in range(len(samples)):
   for j in range(i+1, len(samples)):
       primary_sample = os.path.join(eventDir,samples[i],samples[i])
       secondary_sample = os.path.join(eventDir, samples[j],samples[j])
       submission_file = os.path.join(os.getcwd(),'submission_scripts','miso_compare_{i}_vs_{j}.submission'.format(i=samples[i],j=samples[j]))
       job_file = open(os.path.join(os.getcwd(),'submission_scripts','miso_compare_{i}_vs_{j}.submission'.format(i=samples[i],j=samples[j])),'w')
       job_file.write("#!/bin/bash\n")
       job_file.write("#SBATCH --job-name={}_vs_{}\n".format(samples[i],samples[j]))
       job_file.write("#SBATCH --ntasks=1\n")
       job_file.write("#SBATCH --mem=1G\n")
       job_file.write("#SBATCH --time=10:00:00\n")
       job_file.write("#SBATCH --error=../logs/compare_miso/{}_vs_{}.err\n".format(samples[i],samples[j]))
       job_file.write("#SBATCH --output=../logs/compare_miso/{}_vs_{}.out\n".format(samples[i],samples[j]))
       job_file.write("\n")
       job_file.write("source activate miso_bioconda\n")
       job_file.write("compare_miso --compare-samples {} {} {}\n".format(primary_sample, secondary_sample, outDir))
       job_file.close()
       print(submission_file)
       os.chmod(submission_file,0o777)
       os.chdir(submission_dir)
       os.system("sbatch {}".format(submission_file))
       os.chdir(base_dir)
out_f = open(os.path.join(input[0],'comparisons_launched.txt'),'w')
out_f.close()
